
title: Omnia G Helmi
description: Few posts from time to time

contact:
  linkedin: https://uk.linkedin.com/in/omniagamal
  github: github.com/OmniaGM
  twitter: https://twitter.com/Omnia_G
  skype: skype:omnia_gm?call
  facebook: https://www.facebook.com/omnia.Gm
  googleplus: https://plus.google.com/u/1/+OmniaGamal
  slideShare: http://www.slideshare.net/omniaGm

conf:
  disqus: ogamal

navbar:
  links:
    -
      title: Home
      url: /
    - 
      title: Slides
      url: /slides
    - 
      title: Projects
      url: /projects
    -
      title: Courses
      url: /courses
      
pygments: true
permalink: none
