
title: Omnia's Blog
description: Few posts from time to time

contact:
  linkedin: https://www.linkedin.com/profile/view?id=196388218
  github: github.com/OmniaGM
  twitter: https://twitter.com/Omnia_G
  skype: skype:omnia_gm?call
  facebook: https://www.facebook.com/omnia.Gm
  googleplus: https://plus.google.com/u/1/+OmniaGamal
  slideShare: http://www.slideshare.net/omniaGm

conf:
  disqus: ogamal

navbar:
  links:
    - 
      title: Slides
      url: /slides
    - 
      title: Projects
      url: /projects

pygments: true
permalink: none